### ISSUE TITLE
NPM package broken?

### ISSUE THREAD

**Issue by Devin-Chaves** [mongkuen/gatsby-plugin-page-transitions#1]
Receiving this error on a fresh install.

`npm ERR! code E404
npm ERR! 404 Not Found: gatsby-plugin-page-transition@latest`

**Comment by mongkuen** [comment]
oops did a bad copy/paste on the readme. 

it's "transitions"

`npm install --save gatsby-plugin-page-transitions`

**Comment by mongkuen** [comment]
Updated docs. Let me know if you get it working!
