### ISSUE TITLE
Transition occurs immediately after entering the page

### ISSUE THREAD

**Issue by DigitalGoldfish** [mongkuen/gatsby-plugin-page-transitions#2]
I created a new page and added the PageTransition as described in the Manual (I hope). But the result is not as expected. When I navigate to the page the content fades out immediately till only the white page is left. That repeats whenever I change the page ...

I'll try to upload my page too so that you can see the effect in person.

**Comment by DigitalGoldfish** [comment]
My test is online here: https://cocky-yonath-0b1925.netlify.com/

**Comment by mongkuen** [comment]
Lemme take a look at this, I appreciate you taking the time to let me know!

**Comment by DigitalGoldfish** [comment]
No problem! FYI - I tried updating to react 16 but this didn't change anything. Now I am debugging the plugin code a bit but I am not sure if I will find what's going on as I am not that experienced with react yet. If you cannot reproduce it but have an idea where things might go wrong let me know and I'll have a look

**Comment by mongkuen** [comment]
you're right, it's not react 16. It's actually an issue with react-transition-states with the `transitionStyles` not having an `entered` key. 

Now the question is, why does it work on my site without the key...but breaks on a new project :\

**Comment by DigitalGoldfish** [comment]
Indeed - adding entered to the transitionStyles seems to fix the issue. Maybe a change in the Transition component. One more thing I noticed ... there is error reported in the console because "timeout" is a required property of Transition yet it's value is set to null (transitionTime in props).

**Comment by DigitalGoldfish** [comment]
From my yarn lock

gatsby-plugin-page-transitions@^1.0.5:
  version "1.0.5"
  resolved "https://registry.yarnpkg.com/gatsby-plugin-page-transitions/-/gatsby-plugin-page-transitions-1.0.5.tgz#b4375ad218424bc147f06616117e7848dec00c74"
  dependencies:
    history "^4.7.2"
    prop-types "^15.6.2"
    react-transition-group "^2.4.0"

react-transition-group@^2.4.0:
  version "2.4.0"
  resolved "https://registry.yarnpkg.com/react-transition-group/-/react-transition-group-2.4.0.tgz#1d9391fabfd82e016f26fabd1eec329dbd922b5a"
  dependencies:
    dom-helpers "^3.3.1"
    loose-envify "^1.3.1"
    prop-types "^15.6.2"
    react-lifecycles-compat "^3.0.4"

**Comment by mongkuen** [comment]
Just fixed and published

Upgrade to 1.0.6 and lemme know if it works for you!

**Comment by DigitalGoldfish** [comment]
Problem fixed! Thanks a lot - both for fixing the bug and the plugin.
