### ISSUE TITLE
Multiple animations per transition

### ISSUE THREAD

**Issue by MartinConde** [mongkuen/gatsby-plugin-page-transitions#3]
Not really an issue and more of a question / possible feature request.. Went through the TransitionGroup docs but couldn't really get anything working.

Basically, I want to animate elements in/out at different speeds or even different animations. So instead of the whole container animating at once, it would be kind of staggered animation. Not sure what's better here, to be able to somehow nest transition components or just have classes added depending on the state. The last one should be possible according to their docs but couldn't figure out how to implement it here.

Any pointers for this would be much appreciated! :)

**Comment by mongkuen** [comment]
Hey man, I just made an example project to help you get some bearings on how to approach this. It has an example of animating multiple elements in and out differently. 

https://github.com/mongkuen/gatsby-plugin-page-transitions/tree/master/examples

The `PageTransition` component should still be placed on the root of the page, with the `transitionTime` prop supplied to let the page know how long it needs to pause navigation to the new page for.

Then you can use `react-transition-group`'s `Transition` component directly to make the transitions you need, so you have complete control on duration of the transition. Dot note, the page will still only be held paused for whatever `transitionTime` you supply. 

I've added additional docs in the README explaining what exactly is happening underneath, hope it's helpful. Do know that it'll be more code and complexity than the defaults, which abstracts much of the logic and listeners away.

**Comment by mongkuen** [comment]
Just following up, did you manage to get it working the way you wanted?

**Comment by MartinConde** [comment]
Yes! Works like a charm. Thanks a lot man :) 

The only thing I noticed is..

Lets say I am on a page, and in my nav, click the link of the page I am already on. The animation gets stuck since I guess the entering/entered isn't fired. Doubt many people will click the link they are already on, maybe by accident but just thought to let u know.

**Comment by mongkuen** [comment]
is there code I can be pointed to? It doesn't behave that way on my site, or when I try to replicate the issue. 

In the `PageTransition` component, if the path you're on is the same as the path you're navigating to, nothing should happen. It only flips `this.state.in` if the paths are different.

**Comment by MartinConde** [comment]
Oh ok probably an error on my side then, will try n figure out where I went wrong and if I can't, push to a github repo ;)
