### ISSUE TITLE
Exiting transition styles not passed on exit

### ISSUE THREAD

**Issue by darrenlma** [mongkuen/gatsby-plugin-page-transitions#5]
I am trying to use your plugin to fade out and zoom out on `Link` navigation and fade in with zoom on page entry as

```
defaultStyle={{
  transition: `transform 750ms ease, opacity 1500ms ease`
}}
transitionStyles={{
  entering: {
    transform: `scale(1.05) translateZ(0)`,
    opacity: 0
  },
  entered: {
    transform: `scale(1) translateZ(0)`,
    opacity: 1
  },
  exiting: {
    transform: `scale(0.98) translateZ(0)`,
    opacity: 0
  }
}}
```
However, when a user navigates the `entering` style is active with the page load being initiated immediately. This causes the navigated to page to display immediately with the `entering` style then animating. This can be seen in this gif.

![Image of Gif](https://firebasestorage.googleapis.com/v0/b/appdiscovrbookingscom.appspot.com/o/2018-08-10%2018_20_55.gif?alt=media&token=bebc60b7-6d62-4d60-a044-33caf006fc09) 

It is also worth noting that any style added to the `exiting` styles are not passed. Am I doing something wrong? 

I am using with Gatsby V2 and the page transitions are in my Layout component. I have also tried at the page templates but same applies. Please let me know if you need more information.

**Comment by darrenlma** [comment]
From further investigation it appears that this is caused by Gatsby in V2 latest release now using Reach Router instead of react-router. More can be seen around the topic [here](https://github.com/gatsbyjs/gatsby/issues/5656#issuecomment-411762437).

Any ideas how this plugin can delay route transitions to allow exiting animations for `reach-router`?

**Comment by mongkuen** [comment]
Sorry for being so slow following up, I've been swamped lately. 

There's an influx of v2 issues for the plugins I've written. I finally got around to updating one last night, and I'll be working on this one soon.  

I imagine that reach router has similar history APIs, and [this looks promising](https://reach.tech/router/api/createHistory). Seems you can listen for route changes via `import { createHistory } from "@reach/router"`.

Possibly setting a timeout after detecting a route change, and [navigating imperatively to the next route](https://reach.tech/router/tutorial/09-navigate) might work. 

The only thing I don't see from a fast review of reach router docs is an API similar to react routers `history.block`. There should be some way for reach router to prevent navigation, might have to dive into the source code. 

Reach Router does have an [example of animations](https://reach.tech/router/example/animation), but I'm not sure how well the example will work with gatsby.

**Comment by darrenlma** [comment]
Thanks. I look forward to hearing back with possible solutions.

**Comment by mongkuen** [comment]
Looks like they removed the `replaceHistory` api that was present in Gatsby V1. It'll likely require an entire redo of how the plugin works... I'm not sure how much time I have to work on this, but I may not be able to for a little while.

There's an example of transitions here if you'd like to implement something for yourself. It looks like the code is for V2? 
https://next.gatsbyjs.org/docs/browser-apis/#replaceComponentRenderer

**Comment by darrenlma** [comment]
Thank you for your advice.
